import type { Metadata } from "next";

import Navbar from "./components/Navbar";
import { gowunBatang } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "김서영 | 프론트엔드 포트폴리오",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gowunBatang.className}>
        {/* NOTE - 네비게이션바 */}
        <Navbar />
        <div className="px-5">{children}</div>
      </body>
    </html>
  );
}
